version: "3"

services:
  goss:
    build: .
    image: goss
  sut:
    image: goss
    environment:
      GOSS_FILES_PATH: goss
      GOSS_FILES_STRATEGY: cp
    command: dgoss run goss sleep infinity
    volumes:
      - ./goss:/goss/goss
      - /var/run/docker.sock:/var/run/docker.sock
